apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client-api
    app.kubernetes.io/name: client-api
  name: client-api
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client-api
  strategy: {}
  template:
    metadata:
      labels:
        app: client-api
      annotations:
        instrumentation.opentelemetry.io/inject-python: "otel-collector"
    spec:
      containers:
      - image: vimuchiaroni/client-api:1.2
        name: client-api
        ports:
          - name: http
            containerPort: 8000
        env:
          - name: CART_SERVICE_URL
            value: 'http://cart-api.default.svc.cluster.local:8000'
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: client-api
    app.kubernetes.io/name: client-api
  name: client-api
  namespace: default
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: client-api
  type: ClusterIP